"""add payment fields to orders

Revision ID: 078a2d6bced9
Revises: 7d2e9ea76d5e
Create Date: 2026-07-21 15:44:02.998412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078a2d6bced9'
down_revision: Union[str, Sequence[str], None] = '7d2e9ea76d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'orders',
        sa.Column(
            'payment_status',
            sa.String(),
            nullable=False,
            server_default='unpaid',
        ),
    )
    op.add_column(
        'orders',
        sa.Column('payment_method', sa.String(), nullable=True),
    )
    op.add_column(
        'orders',
        sa.Column('stripe_session_id', sa.String(), nullable=True),
    )
    op.add_column(
        'orders',
        sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    )
    op.create_unique_constraint(
        'uq_orders_stripe_payment_intent_id',
        'orders',
        ['stripe_payment_intent_id'],
    )
    op.create_unique_constraint(
        'uq_orders_stripe_session_id',
        'orders',
        ['stripe_session_id'],
    )
    op.alter_column(
        'orders',
        'payment_status',
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_orders_stripe_session_id',
        'orders',
        type_='unique',
    )
    op.drop_constraint(
        'uq_orders_stripe_payment_intent_id',
        'orders',
        type_='unique',
    )
    op.drop_column('orders', 'stripe_payment_intent_id')
    op.drop_column('orders', 'stripe_session_id')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
