"""add restaurant profile fields

Revision ID: 6075de02b9f5
Revises: 74fed4778a43
Create Date: 2026-07-15 04:07:13.483872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6075de02b9f5'
down_revision: Union[str, Sequence[str], None] = '74fed4778a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('menu_items', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('menu_items', 'image_url')
    op.add_column('restaurants', sa.Column('description', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('cuisine', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('banner_url', sa.String(), nullable=True))
    op.drop_column('restaurants', 'is_active')
    op.drop_column('restaurants', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('restaurants', 'banner_url')
    op.drop_column('restaurants', 'logo_url')
    op.drop_column('restaurants', 'phone')
    op.drop_column('restaurants', 'cuisine')
    op.drop_column('restaurants', 'description')
    op.add_column('menu_items', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('menu_items', 'expires_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('menu_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
