"""Add inventory fields to menu items

Revision ID: 7d2e9ea76d5e
Revises: 43adf4742e7b
Create Date: 2026-07-20 01:00:29.193780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2e9ea76d5e'
down_revision: Union[str, Sequence[str], None] = '43adf4742e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu_items",
        sa.Column(
            "stock_quantity",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "menu_items",
        sa.Column(
            "low_stock_threshold",
            sa.Integer(),
            nullable=False,
            server_default="5",
        ),
    )

    op.add_column(
        "menu_items",
        sa.Column(
            "is_available",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'is_available')
    op.drop_column('menu_items', 'low_stock_threshold')
    op.drop_column('menu_items', 'stock_quantity')
    # ### end Alembic commands ###
